name: PR and List Open PRs

on:
  push:
    branches:
      - test

jobs:
  check-or-create-pr:
    name: Check or Create PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
          echo "REPO_OWNER=$(echo ${{ github.repository }} | cut -d'/' -f1)" >> $GITHUB_ENV
          echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV
          echo "TEST_BRANCH=test" >> $GITHUB_ENV
          echo "DEV_BRANCH=dev" >> $GITHUB_ENV

      - name: Fetch repository ID using GraphQL
        id: get-repo-id
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          QUERY='
          {
            repository(owner: "${REPO_OWNER}", name: "${REPO_NAME}") {
              id
            }
          }'
          
          REPO_ID=$(curl -s -H "Authorization: bearer $GITHUB_TOKEN" -X POST -d "{\"query\":\"$QUERY\"}" https://api.github.com/graphql | sed -n 's/.*"id":"\([^"]*\).*/\1/p')
          echo "REPO_ID=$REPO_ID" >> $GITHUB_ENV

      - name: Check if PR exists from test to dev using GraphQL
        id: check-pr
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          REPO_OWNER: ${{ env.REPO_OWNER }}
          REPO_NAME: ${{ env.REPO_NAME }}
        run: |
          QUERY='
          {
            repository(owner: "${REPO_OWNER}", name: "${REPO_NAME}") {
              pullRequests(states: OPEN, baseRefName: "dev", headRefName: "test", first: 1) {
                edges {
                  node {
                    id
                    title
                  }
                }
              }
            }
          }'

          PR_RESPONSE=$(curl -s -H "Authorization: bearer $GITHUB_TOKEN" -X POST -d "{\"query\":\"$QUERY\"}" https://api.github.com/graphql)
          
          if echo "$PR_RESPONSE" | grep -q '"edges":[]'; then
            echo "No open PR found."
            echo "::set-output name=exists::false"
          else
            echo "Open PR found."
            echo "::set-output name=exists::true"
          fi

      - name: Create PR from test to dev using GraphQL
        if: steps.check-pr.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          REPO_ID: ${{ env.REPO_ID }}
        run: |
          MUTATION='
          mutation {
            createPullRequest(input: {repositoryId: "${REPO_ID}", headRefName: "test", baseRefName: "dev", title: "PR from test to dev", body: "Automatically created PR"}) {
              pullRequest {
                id
                title
              }
            }
          }'
          
          curl -s -H "Authorization: bearer $GITHUB_TOKEN" -X POST -d "{\"query\":\"$MUTATION\"}" https://api.github.com/graphql
