name: PR and List Open PRs

on:
  push:
    branches:
      - test

jobs:
  check-or-create-pr:
    name: Check or Create PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "TEST_BRANCH=test" >> $GITHUB_ENV
          echo "DEV_BRANCH=dev" >> $GITHUB_ENV

      - name: Check if branches differ
        id: check-pr
        run: |
          git fetch origin
          TEST_COMMIT=$(git rev-parse origin/$TEST_BRANCH)
          DEV_COMMIT=$(git rev-parse origin/$DEV_BRANCH)

          if [ "$TEST_COMMIT" = "$DEV_COMMIT" ]; then
            echo "Branches are identical, no PR needed."
            echo "::set-output name=pr_needed::false"
          else
            echo "Branches are different, PR needed."
            echo "::set-output name=pr_needed::true"
          fi

      - name: Suggest creating a PR (manual step)
        if: steps.check-pr.outputs.pr_needed == 'true'
        run: |
          echo "Please create a PR from the '$TEST_BRANCH' to the '$DEV_BRANCH' manually."
          echo "You can create the PR via the GitHub UI."

  list-open-prs:
    name: List Branches (Manual PR tracking)
    needs: check-or-create-pr
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List branches for tracking
        run: |
          echo "Here are the remote branches:"
          git branch -r
