name: PR and List Open PRs

on:
  push:
    branches:
      - test

jobs:
  check-or-create-pr:
    name: Check or Create PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
          echo "TEST_BRANCH=test" >> $GITHUB_ENV
          echo "DEV_BRANCH=dev" >> $GITHUB_ENV

      - name: Check if PR exists from test to dev using GraphQL
        id: check-pr
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          # GraphQL query to check if a PR exists from test to dev
          QUERY='
          {
            repository(owner: "${{ github.repository_owner }}", name: "${{ github.event.repository.name }}") {
              pullRequests(states: OPEN, baseRefName: "dev", headRefName: "test", first: 1) {
                edges {
                  node {
                    id
                    title
                  }
                }
              }
            }
          }'
          
          PR_RESPONSE=$(curl -s -H "Authorization: bearer $GITHUB_TOKEN" -X POST -d "{\"query\":\"$QUERY\"}" https://api.github.com/graphql)
          
          # Check if a PR was found by searching for "edges" in the response
          if echo "$PR_RESPONSE" | grep -q '"edges":[]'; then
            echo "No open PR found."
            echo "::set-output name=exists::false"
          else
            echo "Open PR found."
            echo "::set-output name=exists::true"
          fi

      - name: Create PR from test to dev using GraphQL
        if: steps.check-pr.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          # Mutation to create a new pull request using GraphQL
          MUTATION='
          mutation {
            createPullRequest(input: {repositoryId: "${{ github.event.repository.node_id }}", headRefName: "test", baseRefName: "dev", title: "PR from test to dev", body: "Automatically created PR"}) {
              pullRequest {
                id
                title
              }
            }
          }'
          
          curl -s -H "Authorization: bearer $GITHUB_TOKEN" -X POST -d "{\"query\":\"$MUTATION\"}" https://api.github.com/graphql

  list-open-prs:
    name: List Open Pull Requests
    needs: check-or-create-pr
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List Open PRs using GraphQL
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          # Query to list all open PRs using GraphQL
          QUERY='
          {
            repository(owner: "${{ github.repository_owner }}", name: "${{ github.event.repository.name }}") {
              pullRequests(states: OPEN, first: 10) {
                edges {
                  node {
                    number
                    title
                    author {
                      login
                    }
                  }
                }
              }
            }
          }'
          
          PR_LIST=$(curl -s -H "Authorization: bearer $GITHUB_TOKEN" -X POST -d "{\"query\":\"$QUERY\"}" https://api.github.com/graphql)

          # Extract PR numbers, titles, and authors using sed and awk
          echo "PR Numbers:"
          echo "$PR_LIST" | sed -n 's/.*"number":\([0-9]*\).*/\1/p'

          echo "PR Titles:"
          echo "$PR_LIST" | sed -n 's/.*"title":"\([^"]*\).*/\1/p'

          echo "PR Authors:"
          echo "$PR_LIST" | sed -n 's/.*"login":"\([^"]*\).*/\1/p'

  print-pr-count:
    name: Print PR Count
    needs: list-open-prs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Query for PR count using GraphQL
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          # Query to count all open PRs using GraphQL
          QUERY='
          {
            repository(owner: "${{ github.repository_owner }}", name: "${{ github.event.repository.name }}") {
              pullRequests(states: OPEN) {
                totalCount
              }
            }
          }'
          
          PR_COUNT=$(curl -s -H "Authorization: bearer $GITHUB_TOKEN" -X POST -d "{\"query\":\"$QUERY\"}" https://api.github.com/graphql)
          
          # Extract the PR count
          PR_TOTAL=$(echo "$PR_COUNT" | sed -n 's/.*"totalCount":\([0-9]*\).*/\1/p')

          echo "Total Open PRs: $PR_TOTAL"
