name: PR and List Open PRs

on:
  push:
    branches:
      - test

jobs:
  check-or-create-pr:
    name: Check or Create PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
          echo "TEST_BRANCH=test" >> $GITHUB_ENV
          echo "DEV_BRANCH=dev" >> $GITHUB_ENV

      - name: Check if PR exists from test to dev
        id: check-pr
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: |
          PR_EXISTS=$(gh pr list --base $DEV_BRANCH --head $TEST_BRANCH --state open --json number --jq '.[].number' | wc -l)
          echo "::set-output name=exists::$PR_EXISTS"

      - name: Create PR from test to dev
        if: steps.check-pr.outputs.exists == '0'
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: |
          gh pr create --head $TEST_BRANCH --base $DEV_BRANCH --title "PR from test to dev" --body "Automatically created PR" --repo $GITHUB_REPOSITORY

  list-open-prs:
    name: List Open Pull Requests
    needs: check-or-create-pr
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List Open PRs
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: |
          gh pr list --json number,title,author --jq '.[] | "\(.number) - \(.title) by \(.author.login)"' --repo $GITHUB_REPOSITORY
