name: Last Commit Info

on:
  push:
    branches:
      - test2

jobs:
  generate-last-commit-info:
    name: Generate Last Commit Info
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get last commit info and write to YAML
        run: |
          author=$(git log -1 --pretty=format:'%an')
          committer=$(git log -1 --pretty=format:'%cn')
          date=$(git log -1 --pretty=format:'%cd' --date=iso)
          hash=$(git log -1 --pretty=format:'%H')

          mkdir -p output

          cat <<EOF > output/last_commit.yml
last_commit:
  author: "$author"
  committer: "$committer"
  date: "$date"
  commit_hash: "$hash"
EOF

      - name: Show output file
        run: cat output/last_commit.yml
