name: List Open PRs to CSV

on:
  push:
    branches:
      - main

jobs:
  generate-pr-csv:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository to the workflow
    - name: Checkout the repository
      uses: actions/checkout@v3

    # Step 2: Set up Git configuration
    - name: Set up Git configuration
      run: |
        git config --global user.name "manjushrikrishna"
        git config --global user.email "manjushrik@devtools.in"
    # Step 3: Get open PRs for the repository using GitHub API
    - name: List Open PRs
      id: list_prs
      run: |
        # Get open PRs for the repository and branch
        response=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=main")
        
        # Create CSV file and write headers
        echo "PR Number,Title,User,Created At,URL" > prs.csv
        
        # Extract PR details and append to CSV
        echo "$response" | jq -r '.[] | [.number, .title, .user.login, .created_at, .html_url] | @csv' >> prs.csv
    # Step 4: Move CSV file to main branch
    - name: Move CSV file to main branch
      run: |
        # Checkout the main branch
        git checkout main
        
        # Create a new branch for the commit (optional but safer)
        git checkout -b update-pr-csv
        # Move the CSV file to main branch (already generated in the previous step)
        git add prs.csv
        git commit -m "Add open PRs list CSV"
        git push origin update-pr-csv
    # Step 5: Create a pull request to merge the changes to the main branch
    - name: Create a Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Add Open PRs CSV"
        body: "This pull request adds a CSV file with the list of open PRs."
        base: main
        head: update-pr-csv
