name: Upload to SharePoint

on:
  push:
    branches:
      - main

jobs:
  upload-to-sharepoint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload file to SharePoint
        uses: sjultra/Push2Sharepoint@v3.4
        with:
          username: ${{ secrets.SHAREPOINT_USERNAME }}
          password: ${{ secrets.SHAREPOINT_PASSWORD }}
          file_name: './test.txt'
          full_url: 'https://devtoolsin.sharepoint.com/sites/devtools2'
          target_subfolder: 'Shared Documents/test'
